import type { Metadata } from "next";

import "./globals.css";
import Navber from "@/components/navber";
import { AppProvider } from "@/context/appContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navber />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
